Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('authentification/', include('authentification.urls'), name='authentification'),
    path('reservations/', include('reservations.urls')),
]

Project/reservations/urls.py
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_reservation/', views.create_reservation, name='create_reservation'),
    path('user_reservation/', views.user_reservations, name='user_reservations'),
    path('edit_reservation/<int:reservation_id>/', views.editreservation, name='edit_reservation'),
    path('delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('controlpanel/', views.controlpanel, name='controlpanel'),
]

Project/templates/parts/footer.html
<!-- ***** Footer Start ***** -->
 {% load static %}
 <style>
 .footer {
    text-align: center;
    padding: 2rem 0;
    margin-top: 500px;
}</style>
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-xs-12">
                <div class="right-text-content">
                        <ul class="social-icons">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="https://instagram.com/salim_ahouad"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="logo">
                    <a href="{% url 'index' %}"><img src="{% static 'images/white-logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-4 col-xs-12">
                <div class="left-text-content">
                    <p>© Copyright 2024, all rights reserved
                    
                    <br>Live Dinner</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery -->
<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/owl-carousel.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>
<script src="{% static 'js/scrollreveal.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/imgfix.min.js' %}"></script> 
<script src="{% static 'js/slick.js' %}"></script> 
<script src="{% static 'js/lightbox.js' %}"></script> 
<script src="{% static 'js/isotope.js' %}"></script> 

<!-- Global Init -->
<script src="{% static 'js/custom.js' %}"></script>
<script>

    $(function() {
        var selectedClass = "";
        $("p").click(function(){
        selectedClass = $(this).attr("data-rel");
        $("#portfolio").fadeTo(50, 0.1);
            $("#portfolio div").not("."+selectedClass).fadeOut();
        setTimeout(function() {
          $("."+selectedClass).fadeIn();
          $("#portfolio").fadeTo(50, 1);
        }, 500);
            
        });
    });

</script>
</body>
</html>

Project/templates/parts/navbar.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">

    <title>Live Dinner</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'css/templatemo-klassy-cafe.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">

    </head>
    
    <body>
    
    <!-- ***** Preloader Start ***** -->
    
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url 'index' %}" class="logo">
                            <img src="{% static 'images/klassy-logo.png' %}" align="klassy cafe html template">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url 'index' %}" class="active">Accueil</a></li>
                            <li class="scroll-to-section"><a href="{% url 'index' %}#about">A propos</a></li>
                           	
                        <!-- 
                            <li class="submenu">
                                <a href="javascript:;">Drop Down</a>
                                <ul>
                                    <li><a href="#">Drop Down Page 1</a></li>
                                    <li><a href="#">Drop Down Page 2</a></li>
                                    <li><a href="#">Drop Down Page 3</a></li>
                                </ul>
                            </li>
                        -->
                            <li class="scroll-to-section"><a href="{% url 'index' %}#menu">Menu</a></li>
                            <li class="scroll-to-section"><a href="{% url 'index' %}#chefs">Chefs</a></li> 
                            <!-- <li class=""><a rel="sponsored" href="https://templatemo.com" target="_blank">External URL</a></li> -->
                            {% if request.session.connected %}
                                    <li class="scroll-to-section"><a href="{% url 'reservations:user_reservations' %}">Mes reservations</a></li>
                                    {% if request.session.is_staff %}
                                        <li class="scroll-to-section"><a href="{% url 'reservations:controlpanel' %}">Panneau de control</a></li>
                                    {% endif %}
                                    <li class="scroll-to-section"><a href="{% url 'logout' %}">Déconnexion</a></li>
                            {% else %}
                            <li class="scroll-to-section"><a href="{% url 'login' %}">Se connecter</a></li> 
                            {% endif %}
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->